export const FarmItems = [
  {
    title: "PANIC-WFTM Spooky LP",
    url: "/farms/1",
    cName: "farm-links",
    symbol1: "PANIC",
    symbol2: "WFTM",
    boost: "12",
  },
  {
    title: "WFTM-DAI Panic Variable LP",
    url: "/farms/2",
    cName: "farm-links",
    symbol1: "WFTM",
    symbol2: "DAI",
    boost: "3",
  },
  {
    title: "BTC-ETH Panic Variable LP",
    url: "/farms/3",
    cName: "farm-links",
    symbol1:"BTC",
    symbol2:"ETH",
    boost: "4",
  },
  {
    title: "YFI-ETH Panic Variable LP",
    url: "/farms/4",
    cName: "farm-links",
    symbol1: "YFI",
    symbol2: "ETH",
    boost: "0.5",
  },
  {
    title: "BTC-renBTC Panic Stable LP",
    url: "/farms/5",
    cName: "farm-links",
    symbol1: "BTC",
    symbol2: "renBTC",
    boost: "0.4",
  },
  {
    title: "USDC-DAI Panic Stable LP",
    url: "/farms/6",
    cName: "farm-links",
    symbol1: "USDC",
    symbol2: "DAI",
    boost: "0.1",
  },
  {
    title: "WFTM-ETH Panic Variable LP",
    url: "/farms/7",
    cName: "farm-links",
    symbol1: "WFTM",
    symbol2: "ETH",
    boost: "0.4",
  },
  {
    title: "WFTM-BTC Panic Variable LP",
    url: "/farms/8",
    cName: "farm-links",
    symbol1: "WFTM",
    symbol2: "BTC",
    boost: "0.4",
  },
  {
    title: "WFTM-USDC Panic Variable LP",
    url: "/farms/9",
    cName: "farm-links",
    symbol1: "WFTM",
    symbol2: "USDC",
    boost: "0.4",
  },
  {
    title: "WFTM-XFTM Panic Variable LP",
    url: "/farms/10",
    cName: "farm-links",
    symbol1: "WFTM",
    symbol2: "XFTM",
    boost: "Farm disabled",
  },
];
