export const FarmItems = [
  {
    title: "PANIC-WFTM Spooky LP",
    url: "/farms/1",
    cName: "farm-links",
    symbol1: "PANIC",
    symbol2: "yvWFTM",
    boost: "12",
  },
  {
    title: "yvWFTM-yvDAI Panic Variable LP",
    url: "/farms/2",
    cName: "farm-links",
    symbol1: "yvWFTM",
    symbol2: "yvDAI",
    boost: "3",
  },
  {
    title: "yvWBTC-yvWETH Panic Variable LP",
    url: "/farms/3",
    cName: "farm-links",
    symbol1:"yvWBTC",
    symbol2:"yvWETH",
    boost: "4",
  },
  {
    title: "yvYFI-yvWETH Panic Variable LP",
    url: "/farms/4",
    cName: "farm-links",
    symbol1: "yvYFI",
    symbol2: "yvWETH",
    boost: "1",
  },
  {
    title: "yvWBTC-renBTC Panic Stable LP",
    url: "/farms/5",
    cName: "farm-links",
    symbol1: "yvWBTC",
    symbol2: "renBTC",
    boost: "0.4",
  },
  {
    title: "yvUSDC-yvDAI Panic Stable LP",
    url: "/farms/6",
    cName: "farm-links",
    symbol1: "yvUSDC",
    symbol2: "yvDAI",
    boost: "0.1",
  },
  {
    title: "yvWFTM-yvWETH Panic Variable LP",
    url: "/farms/7",
    cName: "farm-links",
    symbol1: "yvWFTM",
    symbol2: "yvWETH",
    boost: "0.7",
  },
  {
    title: "yvWFTM-yvWBTC Panic Variable LP",
    url: "/farms/8",
    cName: "farm-links",
    symbol1: "yvWFTM",
    symbol2: "yvWBTC",
    boost: "0.7",
  },
  {
    title: "yvWFTM-yvUSDC Panic Variable LP",
    url: "/farms/9",
    cName: "farm-links",
    symbol1: "yvWFTM",
    symbol2: "yvUSDC",
    boost: "0.7",
  },
];
