export const FarmItems = [
  {
    title: "PANIC-WFTM Spooky LP",
    url: "/farms/1",
    poolid: 1,
    cName: "farm-links",
    symbol1: "PANIC",
    symbol2: "WFTM",
    boost: "5.5",
  },
  {
    title: "WFTM-DAI Panic Variable LP",
    url: "/farms/2",
    poolid: 2,
    cName: "farm-links",
    symbol1: "WFTM",
    symbol2: "DAI",
    boost: "3.23",
  },
  {
    title: "BTC-ETH Panic Variable LP",
    url: "/farms/3",
    poolid: 3,
    cName: "farm-links",
    symbol1: "BTC",
    symbol2: "ETH",
    boost: "7.67",
  },
  {
    title: "YFI-ETH Panic Variable LP",
    url: "/farms/4",
    poolid: 4,
    cName: "farm-links",
    symbol1: "YFI",
    symbol2: "ETH",
    boost: "0.5",
  },
  {
    title: "BTC-renBTC Panic Stable LP",
    url: "/farms/5",
    poolid: 5,
    cName: "farm-links",
    symbol1: "BTC",
    symbol2: "renBTC",
    boost: "0.2",
  },
  {
    title: "USDC-DAI Panic Stable LP",
    url: "/farms/6",
    poolid: 6,
    cName: "farm-links",
    symbol1: "USDC",
    symbol2: "DAI",
    boost: "0.1",
  },
  {
    title: "WFTM-ETH Panic Variable LP",
    url: "/farms/7",
    poolid: 7,
    cName: "farm-links",
    symbol1: "WFTM",
    symbol2: "ETH",
    boost: "0.6",
  },
  {
    title: "WFTM-BTC Panic Variable LP",
    url: "/farms/8",
    poolid: 8,
    cName: "farm-links",
    symbol1: "WFTM",
    symbol2: "BTC",
    boost: "0.73",
  },
  {
    title: "WFTM-USDC Panic Variable LP",
    url: "/farms/9",
    poolid: 9,
    cName: "farm-links",
    symbol1: "WFTM",
    symbol2: "USDC",
    boost: "2.78",
  },
  {
    title: "fBEETS-USDC Panic Variable LP",
    url: "/farms/11",
    poolid: 11,
    cName: "farm-links",
    symbol1: "fBEETS",
    symbol2: "USDC",
    boost: "1.9",
  },
  {
    title: "BOO-FTM Panic Variable LP",
    url: "/farms/12",
    poolid: 12,
    cName: "farm-links",
    symbol1: "BOO",
    symbol2: "WFTM",
    boost: "1",
  },
  {
    title: "PANIC-bePANIC Panic Stable LP",
    url: "/farms/13",
    poolid: 13,
    cName: "farm-links",
    symbol1: "PANIC",
    symbol2: "bePANIC",
    boost: "2.64",
  },
  {
    title: "BELUGA-FTM Panic Variable LP",
    url: "/farms/14",
    poolid: 14,
    cName: "farm-links",
    symbol1: "BELUGA",
    symbol2: "WFTM",
    boost: "2.33",
  },
  {
    title: "PANIC-FTM Panic Variable LP",
    url: "/farms/15",
    poolid: 15,
    cName: "farm-links",
    symbol1: "PANIC",
    symbol2: "WFTM",
    boost: "1",
  },
  {
    title: "oxSOLID-SOLID Panic Stable LP",
    url: "/farms/16",
    poolid: 16,
    cName: "farm-links",
    symbol1: "SOLID",
    symbol2: "oxSOLID",
    boost: "2.32",
  },
  {
    title: "Never PANIC yearn boosted Beets LP",
    url: "/farms/17",
    poolid: 17,
    cName: "farm-links",
    symbol1: "PANIC",
    symbol2: "WFTM",
    boost: "5.5",
  },
  {
    title: "fBEETS-beBEETS Panic Variable LP",
    url: "/farms/18",
    poolid: 18,
    cName: "farm-links",
    symbol1: "fBEETS",
    symbol2: "beBEETS",
    boost: "2",
  },
];
